CREATE SCHEMA `mathFLAT` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;

DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT
(
    `ID`           BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '학생 ID',
    `NAME`         VARCHAR(255)    NOT NULL    COMMENT '학생 이름',
    `UPDATE_TIME`  DATETIME        NULL        COMMENT '갱신 날짜',
    `INSERT_TIME`  DATETIME        NULL        COMMENT '등록 날짜',
    PRIMARY KEY (ID),
    INDEX `NAME` (`NAME`)
);

DROP TABLE IF EXISTS SUBJECT;
CREATE TABLE SUBJECT
(
    `ID`    BIGINT                  NOT NULL    COMMENT '과목 ID',
    `NAME`  VARCHAR(45)             NOT NULL    COMMENT '과목이름',
    PRIMARY KEY (ID),
    UNIQUE INDEX NAME (`NAME`)
);

DROP TABLE IF EXISTS SCORE;
CREATE TABLE SCORE
(
    `ID`           BIGINT               NOT NULL    AUTO_INCREMENT COMMENT '점수 ID',
    `STUDENT_ID`   BIGINT               NOT NULL    COMMENT '학생 ID',
    `SUBJECT_ID`   BIGINT               NOT NULL    COMMENT '과목 ID',
    `SCORE`        `INT`                NOT NULL    COMMENT '과목 ID',
    `UPDATE_TIME`  DATETIME             NULL        COMMENT '갱신 날짜',
    `INSERT_TIME`  DATETIME             NULL        COMMENT '등록 날짜',
    PRIMARY KEY (ID),
    INDEX `STUDENT_ID` (`STUDENT_ID`)
);

ALTER TABLE SCORE
    ADD CONSTRAINT FK_SCORE_STUDENT_ID_STUDENT_ID FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SCORE
    ADD CONSTRAINT FK_SCORE_SUBJECT_ID_SUBJECT_ID FOREIGN KEY (SUBJECT_ID)
        REFERENCES SUBJECT (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;


